version: "3.7"
services:
  mongodb:
    image: "mongo:4.4.3"
    restart: on-failure
    ports:
      - "27017:27017"

  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    links:
      - mongodb:mongodb

volumes:
  mongodb-data:
